// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	DocID               string `json:"docID"`
	SecCode             string `json:"secCode"`
	FilerName           string `json:"filerName"`
	DocDescription      string `json:"docDescription"`
	SubmitDatetime      string `json:"submitDatetime"`
	AvgAge              string `json:"avgAge"`
	AvgYearOfService    string `json:"avgYearOfService"`
	AvgAnnualSalary     string `json:"avgAnnualSalary"`
	NumberOfEmployees   string `json:"numberOfEmployees"`
	EmployeeInformation string `json:"employeeInformation"`
}

type CompanyFilter struct {
	FilerName       *string `json:"filerName,omitempty"`
	AvgAnnualSalary *string `json:"avgAnnualSalary,omitempty"`
}

type Query struct {
}
